### ISSUE TITLE
BIE - UI - Display language and search term when searching on IEK language terms

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/generic-bie#4]
Not sure if this should be in generic-bie or one of the other bie repos - TBD

As a person using an IEK language term for searching
I want to see the term I used in he search results 
So that I can confirm the term I used was correct

Requirements:
1. Display the language and language term in the search results
2. Preserve the existing formatting conventions for the font, size and italicsation
3. If there is more than one IEK language with the term, display them one under the other.  Display in Alphabetical order by Language.

**Comment by m-hope** [comment]
I think this is more of a generic "how should we present search results in the ALA" and should probably be left until we have some UI/UX consultant input.

**Comment by m-hope** [comment]
Specific task to complete: need to confirm that searching on an IEK language term will return a "Common name" entry in the search results, however the reference for all IEK names should be "Indigenous language name" not "Common Name".

**Comment by m-hope** [comment]
Optional task to complete (and probably needs confirmation from Dave/Nick): adjust the SOLR search config to allow the replacement of 'anglised' versions of accented characters (eg: results for Mārū should be returned in the search results if the search term "Maru" is used).

**Comment by RobinaSanderson** [comment]
Code review and test by data management team, moving to ready to be released column for IEK project.
